import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    marginBottom: 20,
  },
  loadingContainer: {
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#e0e0e0',
    fontSize: 16,
  },
  carouselContent: {
    flexDirection: 'row',
    paddingHorizontal: 16,
  },
  cardContainer: {
    alignItems: 'center',
    overflow: 'visible',
    paddingTop: 10,
  },
  card: {
    width: '100%',
    aspectRatio: 0.67,
    borderRadius: 12,
    backgroundColor: '#1a1a1a',
    overflow: 'visible',        
    elevation: 6,               
    shadowColor: '#000',        
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
  },
  cardImage: {
    width: '100%',
    height: '100%',
  },
  discountTag: {
    position: 'absolute',
    top: -10,          
    left: 0,
    backgroundColor: '#2dc653',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderBottomRightRadius: 0,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    zIndex: 10,
  },
  discountText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
  priceTag: {
    position: 'absolute',
    bottom: -10,
    right: -4,
    backgroundColor: '#051923',
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 8,
    borderTopLeftRadius: 0,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    zIndex: 10,
  },
  priceText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 13,
  },
  gameName: {
    marginTop: 10,
    color: '#e0e0e0',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    width: '100%',
  },
});