@startuml usuario-jogo
left to right direction
skinparam packageStyle rectangle
actor Jogador as user

rectangle "Aplicativo do Jogo" {
  usecase "Acessar Tela de Administrar Party" as UC1
  usecase "Acessar Loja de Personagens" as UC2
  usecase "Comprar Personagem" as UC3
  usecase "Selecionar Personagens para Party" as UC4
  usecase "Iniciar Jogo" as UC5
  usecase "Receber Recompensa" as UC6
  
  UC1 .> UC4 : inclui
}

rectangle "Sistema do Jogo" {
  usecase "Receber Informações da Party" as UC7
  usecase "Ajustar Party" as UC8
  usecase "Encerrar Jogo" as UC9
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
user --> UC6

UC5 --> UC7
UC7 --> UC8
UC9 --> UC6

@enduml
