@startuml administrador
left to right direction
actor Administrador

(Cadastrar Jogo) --> (Adicionar Key ao Estoque)
(Atualizar Preço)
(Banir Usuário)
(Visualizar Pedidos) --> (Cancelar Pedido)
(Responder Ticket)

Administrador --> (Cadastrar Jogo)
Administrador --> (Atualizar Preço)
Administrador --> (Visualizar Pedidos)
Administrador --> (Gerar Relatório de Vendas)
Administrador --> (Banir Usuário)
Administrador --> (Responder Ticket)

@enduml