@startuml processo-compra
left to right direction
actor Cliente

rectangle "Compra" {
  (Selecionar Jogo) --> (Ver Detalhes)
  (Adicionar ao Carrinho) --> (Editar Quantidade)
  (Finalizar Compra) --> (Selecionar Pagamento)
  (Receber Key por Email)

  Cliente --> (Selecionar Jogo)
  Cliente --> (Adicionar ao Carrinho)
  Cliente --> (Finalizar Compra)
  Cliente --> (Receber Key por Email)
}
@enduml