@startuml gestao-estoque
left to right direction
actor Administrador

rectangle "Estoque" {
  (Importar Lote de Keys)
  (Verificar Keys Disponíveis)
  (Invalidar Key Resgatada)

  Administrador --> (Importar Lote de Keys)
  Administrador --> (Verificar Keys Disponíveis)
  Administrador --> (Invalidar Key Resgatada)
}
@enduml